
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "springboot-ocdemo.fullname" . }}"
  labels:
    {{- include "springboot-ocdemo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "springboot-ocdemo.name" . }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "springboot-ocdemo.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: "{{ include "springboot-ocdemo.name" . }}"
          image: "image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ include "springboot-ocdemo.fullname" . }}:latest"
          imagePullPolicy: "{{ .Values.image.pullPolicy | default "Always" }}"
          ports:
            - containerPort: {{ .Values.service.port | default 8080 }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

