apiVersion: v1
kind: Service
metadata:
  name: "{{ include "springboot-ocdemo.fullname" . }}"
  labels:
    {{- include "springboot-ocdemo.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: "{{ include "springboot-ocdemo.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.port | default 8080 }}   